name: Use Secrets in Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a Secret
      env:
        MySecret: ${{ secrets.MySecret }}
      run: |
        echo "MySecret is: $MySecret"
